-- HarryShop E-Commerce Analytics Queries



-- 1. Total Revenue Generated
-- Calculates the overall revenue from all successful payments

SELECT 
    SUM(amount) AS total_revenue
FROM payments;


-- 2. Revenue Generated by Each Product
-- Displays revenue contribution of every product
-- considering only delivered orders

SELECT 
    p.product_name,
    SUM(oi.quantity * p.price) AS revenue
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
JOIN orders o 
    ON oi.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_name
ORDER BY revenue DESC;


-- 3. Top Customers by Total Spending
-- Identifies customers with the highest purchase value

SELECT 
    c.customer_name,
    SUM(p.amount) AS total_spent
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN payments p 
    ON o.order_id = p.order_id
GROUP BY c.customer_name
ORDER BY total_spent DESC;


-- 4. Best Selling Products
-- Shows products with the highest quantity sold

SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC;


-- 5. Cancelled Orders Analysis
-- Counts the total number of cancelled orders

SELECT 
    COUNT(*) AS cancelled_orders
FROM orders
WHERE order_status = 'Cancelled';
